---
- name: Install Container Platform Engine and AWS CLI
  dnf:
    name:
      - docker
      - awscli
    state: present
    update_cache: yes

- name: Ensure Docker CLI Plugins Directory Exists
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose CLI Plugin
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ ansible_architecture }}"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'

- name: Launch Container Lifecycle Daemon Engine
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Append Pipeline Execution Account to Local Daemon Socket Access Group
  user:
    name: ec2-user
    groups: docker
    append: yes
